#
# script.py.mako
#
# Alembic migration script template
#

"""
Revision ID: 31948616a65b
Revises: 20251023_merge_heads
Create Date: 2025-12-19 18:48:44.756728+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31948616a65b'
down_revision = '20251023_merge_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marine_vessel', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('marine_vessel', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marine_vessel', 'width')
    op.drop_column('marine_vessel', 'length')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
