#
# script.py.mako
#
# Alembic migration script template
#

"""
Revision ID: 341945603358
Revises: d598f29304a0
Create Date: 2026-02-17 19:19:55.556969+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341945603358'
down_revision = 'd598f29304a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marine_country',
    sa.Column('mid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('pais', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mid', name=op.f('pk_marine_country'))
    )
    op.create_index('ix_marine_country_mid', 'marine_country', ['mid'], unique=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_marine_country_mid', table_name='marine_country')
    op.drop_table('marine_country')
    # ### end Alembic commands ###

