#
# script.py.mako
#
# Alembic migration script template
#

"""
Revision ID: a3e105d92cf8
Revises: 86acc5b0d153
Create Date: 2026-02-04 15:58:48.678720+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e105d92cf8'
down_revision = '86acc5b0d153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Port number unique (index already exists from previous migration, but need it to be unique)
    op.drop_index('ix_marine_port_port_number', table_name='marine_port')
    op.create_index(op.f('ix_marine_port_port_number'), 'marine_port', ['port_number'], unique=True)
    
    # Unlocode non-unique
    op.drop_index('ix_marine_port_unlocode', table_name='marine_port')
    op.create_index(op.f('ix_marine_port_unlocode'), 'marine_port', ['unlocode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marine_port_unlocode'), table_name='marine_port')
    op.create_index('ix_marine_port_unlocode', 'marine_port', ['unlocode'], unique=True)
    
    op.drop_index(op.f('ix_marine_port_port_number'), table_name='marine_port')
    op.create_index('ix_marine_port_port_number', 'marine_port', ['port_number'], unique=False)
    # ### end Alembic commands ###
