#
# script.py.mako
#
# Alembic migration script template
#

"""
Revision ID: d598f29304a0
Revises: a3e105d92cf8
Create Date: 2026-02-04 16:03:51.579641+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd598f29304a0'
down_revision = 'a3e105d92cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marine_port', 'unlocode',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marine_port', 'unlocode',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
