#
# script.py.mako
#
# Alembic migration script template
#

"""
Revision ID: eee07593189e
Revises: 341945603358
Create Date: 2026-02-17 19:40:21.765697+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee07593189e'
down_revision = '341945603358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Rename existing flag column to flag_old (backup)
    op.alter_column('marine_vessel', 'flag', new_column_name='flag_old')
    
    # Step 2: Create new flag column as Integer with foreign key
    op.add_column('marine_vessel', sa.Column('flag', sa.Integer(), nullable=True))
    
    # Step 3: Add foreign key constraint
    op.create_foreign_key(
        op.f('fk_marine_vessel_flag_marine_country'), 
        'marine_vessel', 
        'marine_country', 
        ['flag'], 
        ['mid']
    )
    
    # Note: Data population will be done via separate script
    # The flag_old column will be kept for now as a backup
    
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Drop foreign key constraint
    op.drop_constraint(op.f('fk_marine_vessel_flag_marine_country'), 'marine_vessel', type_='foreignkey')
    
    # Step 2: Drop the new flag column
    op.drop_column('marine_vessel', 'flag')
    
    # Step 3: Rename flag_old back to flag
    op.alter_column('marine_vessel', 'flag_old', new_column_name='flag')
    
    # ### end Alembic commands ###

