#
# script.py.mako
#
# Alembic migration script template
#

"""
Revision ID: f110c421d44f
Revises: 31948616a65b
Create Date: 2026-01-12 19:13:06.803412+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'f110c421d44f'
down_revision = '31948616a65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_pending')
    op.drop_table('contact_requests')
    op.alter_column('activation_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_activation_tokens_token_hash'), 'activation_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_activation_tokens_user_id'), 'activation_tokens', ['user_id'], unique=False)
    op.alter_column('marine_port', 'coords',
               existing_type=sa.TEXT(),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_index('idx_marine_port_coords', 'marine_port', ['coords'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_marine_port_unlocode'), 'marine_port', ['unlocode'], unique=True)
    op.create_index('ix_marine_port_unlocode_name', 'marine_port', ['unlocode', 'name'], unique=False)
    op.drop_column('marine_port', 'coords_geom')
    op.drop_column('marine_port', 'ext_refs_jsonb')
    op.drop_column('marine_port', 'coords_new')

    op.drop_column('marine_vessel', 'ext_refs_jsonb')
    op.drop_constraint('uq_permissions_slug', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_slug'), 'permissions', ['slug'], unique=True)
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.alter_column('release_sections', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_release_sections_release_id'), 'release_sections', ['release_id'], unique=False)
    op.create_index('ix_release_version_type', 'releases', ['version', 'type'], unique=True)
    op.create_index(op.f('ix_releases_version'), 'releases', ['version'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.drop_constraint('uq_roles_slug', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.drop_index('ix_sessiontoken_token_hash', table_name='session_tokens')
    op.drop_index('ix_sessiontoken_user_id', table_name='session_tokens')
    op.drop_index('ix_sessiontoken_user_id_revoked', table_name='session_tokens')
    op.create_index(op.f('ix_session_tokens_token_hash'), 'session_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_session_tokens_user_id'), 'session_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.alter_column('usage_counters', 'used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_usage_counters_feature_key'), 'usage_counters', ['feature_key'], unique=False)
    op.create_index(op.f('ix_usage_counters_subscription_id'), 'usage_counters', ['subscription_id'], unique=False)
    op.create_unique_constraint('uq_usage_period', 'usage_counters', ['subscription_id', 'feature_key', 'period_start'])
    op.add_column('user', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('billing_period', sa.String(length=20), nullable=True))
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'is_superadmin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.create_foreign_key(op.f('fk_user_plan_id_plans'), 'user', 'plans', ['plan_id'], ['id'])
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_pref_user_key', 'user_preferences', ['user_id', 'key'])
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.alter_column('vessel_snapshot', 'last_geom',
               existing_type=sa.TEXT(),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_index('idx_vessel_snapshot_last_geom', 'vessel_snapshot', ['last_geom'], unique=False, postgresql_using='gist')
    op.drop_column('vessel_snapshot', 'last_geom_geom')
    op.drop_column('vessel_snapshot', 'last_geom_new')
    op.alter_column('vessel_state', 'geom',
               existing_type=sa.TEXT(),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_index('idx_vessel_state_geom', 'vessel_state', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_vessel_state_geom_gist', 'vessel_state', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_vessel_state_mmsi'), 'vessel_state', ['mmsi'], unique=False)
    op.create_index('ix_vessel_state_mmsi_ts', 'vessel_state', ['mmsi', 'ts'], unique=False)
    op.create_index(op.f('ix_vessel_state_ts'), 'vessel_state', ['ts'], unique=False)
    op.drop_column('vessel_state', 'geom_new')
    op.drop_column('vessel_state', 'geom_geom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_state', sa.Column('geom_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.add_column('vessel_state', sa.Column('geom_new', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vessel_state_ts'), table_name='vessel_state')
    op.drop_index('ix_vessel_state_mmsi_ts', table_name='vessel_state')
    op.drop_index(op.f('ix_vessel_state_mmsi'), table_name='vessel_state')
    op.drop_index('ix_vessel_state_geom_gist', table_name='vessel_state', postgresql_using='gist')
    op.drop_index('idx_vessel_state_geom', table_name='vessel_state', postgresql_using='gist')
    op.alter_column('vessel_state', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('vessel_snapshot', sa.Column('last_geom_new', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vessel_snapshot', sa.Column('last_geom_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_index('idx_vessel_snapshot_last_geom', table_name='vessel_snapshot', postgresql_using='gist')
    op.alter_column('vessel_snapshot', 'last_geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_constraint('uq_user_pref_user_key', 'user_preferences', type_='unique')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_constraint(op.f('fk_user_plan_id_plans'), 'user', type_='foreignkey')
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user', 'is_superadmin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.drop_column('user', 'billing_period')
    op.drop_column('user', 'plan_id')
    op.drop_constraint('uq_usage_period', 'usage_counters', type_='unique')
    op.drop_index(op.f('ix_usage_counters_subscription_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_feature_key'), table_name='usage_counters')
    op.alter_column('usage_counters', 'used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_session_tokens_user_id'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_token_hash'), table_name='session_tokens')
    op.create_index('ix_sessiontoken_user_id_revoked', 'session_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index('ix_sessiontoken_user_id', 'session_tokens', ['user_id'], unique=False)
    op.create_index('ix_sessiontoken_token_hash', 'session_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.create_unique_constraint('uq_roles_slug', 'roles', ['slug'])
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_releases_version'), table_name='releases')
    op.drop_index('ix_release_version_type', table_name='releases')
    op.drop_index(op.f('ix_release_sections_release_id'), table_name='release_sections')
    op.alter_column('release_sections', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_index(op.f('ix_permissions_slug'), table_name='permissions')
    op.create_unique_constraint('uq_permissions_slug', 'permissions', ['slug'])
    op.add_column('marine_vessel', sa.Column('ext_refs_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_marine_vessel_mmsi'), table_name='marine_vessel')
    op.drop_index(op.f('ix_marine_vessel_imo'), table_name='marine_vessel')
    op.create_index('marine_vessel_mmsi_idx', 'marine_vessel', ['mmsi'], unique=True)
    op.add_column('marine_port', sa.Column('coords_new', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('marine_port', sa.Column('ext_refs_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('marine_port', sa.Column('coords_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_index('ix_marine_port_unlocode_name', table_name='marine_port')
    op.drop_index(op.f('ix_marine_port_unlocode'), table_name='marine_port')
    op.drop_index('idx_marine_port_coords', table_name='marine_port', postgresql_using='gist')
    op.alter_column('marine_port', 'coords',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_activation_tokens_user_id'), table_name='activation_tokens')
    op.drop_index(op.f('ix_activation_tokens_token_hash'), table_name='activation_tokens')
    op.alter_column('activation_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_table('contact_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('employees', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('subscription', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('geographic', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_contact_requests')
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('form_pending',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('employees', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('subscription', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('geographic', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_form_pending')
    )
    # ### end Alembic commands ###
