name: Backend CI

on:
  push:
    paths:
      - 'backend-services/**'
  pull_request:
    paths:
      - 'backend-services/**'

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend-services/requirements.txt
      - name: Run quick lint (flake8 if available)
        run: |
          if command -v flake8 >/dev/null 2>&1; then flake8 backend-services || true; else echo "flake8 not installed"; fi
      - name: Run tests (if any)
        run: |
          if [ -d backend-services/tests ]; then pytest -q backend-services/tests || true; else echo "no backend tests"; fi
